# Generated by Django 3.1.3 on 2020-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasMedicas', '0001_initial'),
    ]


